export const products = [
  {
    id: 1,
    slug: "keripik-kripik-singkong-bumbu-rujak-1kg-mutiara-abadi",
    name: "Keripik kripik singkong bumbu rujak 1kg Mutiara Abadi",
    price: 28.900,
    sold: 2100,
    rating: 4.9,
    image: "/images/products/kripik1.jpg",
    category: "keripik",
    bestseller: true,
  },
  {
    id: 2,
    slug: "matcha-latte",
    name: "Matcha Latte",
    price: 25000,
    sold: 980,
    rating: 4.8,
    image: "/images/products/matcha.png",
    category: "Minuman",
    bestseller: true,
  },
  {
    id: 3,
    slug: "croissant",
    name: "Butter Croissant",
    price: 22000,
    sold: 540,
    rating: 4.8,
    image: "/images/products/croissant.png",
    category: "Snack",
    bestseller: false,
  },
  {
    id: 4,
    slug: "americano",
    name: "Americano",
    price: 20000,
    sold: 1100,
    rating: 4.9,
    image: "/images/products/americano.png",
    category: "Kopi",
    bestseller: true,
  },
];