name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPSBIZNET }}
          username: ${{ secrets.VPS_NAME }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            cd ~/demo-marketplace

            echo "=== Update source code ==="
            git fetch origin
            git reset --hard origin/main

            echo "=== Install dependencies ==="
            npm ci

            echo "=== Prisma generate ==="
            npx prisma generate

            echo "=== Prisma migration ==="
            npx prisma migrate deploy

            echo "=== Build application ==="
            npm run build

            echo "=== Restart application ==="
            pm2 reload toko

            echo "=== DEPLOY SUCCESS ==="