name: Test VPS Connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPSBIZNET }}
          username: ${{ secrets.VPS_NAME }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            echo "SSH connection berhasil!"
            whoami
            hostname
            pwd